[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]
#config = { userLanguages = { astro = "html", "*.astro" = "html" } }

[language-server.typescript-language-server]
command = "vtsls"
args = ["--stdio"]

[language-server.rescript-language-server]
config = { inlayHints=  { enable = true } }

[[language]]
name = "typescript"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
roots = ["package.json"]
name = "jsx"
language-servers = [ "tailwindcss-ls", "typescript-language-server" ]

[[language]]
roots = ["package.json"]
name = "tsx"
language-servers = [ "tailwindcss-ls", "typescript-language-server" ]

[[language]]
name = "html"
language-servers = [ "tailwindcss-ls", "vscode-html-language-server" ]

[[language]]
name = "css"
language-servers = [ "tailwindcss-ls", "vscode-css-language-server" ]


[[language]]
roots = ["rescript.json"]
name = "rescript"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "rescript"] }
language-servers = [ "rescript-language-server" ]
file-types = ["resi"]

[[language]]
roots = ["rescript.json"]
name = "rescript"
file-types = ["res"]
language-servers = [ "tailwindcss-ls", "rescript-language-server" ]
